### PR TITLE
Upgrade to Pandoc version 2.3.1

### PR DESCRIPTION
**Pull request by coryschires**
Same upgrade process as always. For details see https://github.com/scholastica/pandoc-buildpack/blob/master/README.md

### CODE REVIEW

**Comment by georgediaz88** [comment]
LGTM

**Comment by lizdenhup** [comment]
LGTM!

**Comment by raquelcps** [comment]
LGTM

**Comment by coryschires** [comment]
**Follow up**

I've updated the Pandoc version on staging, demo, and production.

**Pull request merged**
